### ISSUE TITLE
Doc example seems broken

### ISSUE THREAD

**Issue by pjlsergeant** [arodland/CLI-Osprey#26]
```
$ cpm install CLI::Osprey
DONE install CLI::Osprey is up to date. (0.05)
```

cribbed from the docs:

```
package Hello;
use Moo;
use CLI::Osprey;

option 'message' => (
    is => 'ro',
    format => 's',
    doc => 'The message to display',
    default => 'Hello world!',
);

sub run {
    my ($self) = @_;
    print $self->message, "\n";
}

1;
```

and

```
#!/usr/bin/env perl
use lib 'lib';
use Hello;
Hello->new_with_options->run;
```

Output:
```
$ ./hello.pl -m asdf
Unknown option: m
Unknown option: e
Unknown option: s
Unknown option: s
Unknown option: a
Unknown option: g
Unknown option: e
Usage: hello.pl [-h] [--message string] -h --help --man at /Users/pjlsergeant/perl5/perlbrew/perls/perl-5.30.2/lib/site_perl/5.30.2/CLI/Osprey/Descriptive/Usage.pm line 329.
```

That doesn't feel like it can possibly be expected behaviour

**Comment by arodland** [comment]
I just pushed a change that "fixes" this... in the next release, `./hello.pl -m asdf` will give `Unknown option: m`.

The reason for this is that abbreviation is only intended to work for "long" --options. `--message` can abbreviate to `--mess`, and even `--m`, but not `-m`.

If you want `-m` to work then apply `short => 'm'` to your option specifier. This was prevented from working properly by the same bug that gave you your weird error, but will be fixed in the next release.
